
name: British Antarctic Survey
description: British Antarctic Survey (BAS) delivers world-leading interdisciplinary research in the Polar Regions
avatar: https://avatars0.githubusercontent.com/u/3471666?v=3&s=200

url: https://antarctica.github.io
baseurl: 

